services:
  tools:
    container_name: converge_tools
    image: img/converge-tools
    build:
      context: .
      dockerfile: Dockerfile
      args:
        ALPINE_IMAGE: $ALPINE_IMAGE
        GOLANG_IMAGE: $GOLANG_IMAGE
        GOFUMPT_VERSION: $GOFUMPT_VERSION
        GOLANGCI_LINT_VERSION: $GOLANGCI_LINT_VERSION
        PKGSITE_VERSION: $PKGSITE_VERSION
    ports:
      - "3030:3030"
    volumes:
      - ./:/workspace
      - go_cache:/go/.cache
      - $GOPATH/pkg/mod:/go/pkg/mod

volumes:
  go_cache:

networks:
  tools:
    internal: true
