name: Test

on: [ push, workflow_dispatch ]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Run tests
        run: |
          make test/full TOOLS=
